### ISSUE TITLE
How to visualize the results of evaluation

### ISSUE THREAD

**Issue by LiangZhao13** [RobustFieldAutonomyLab/Distributional_RL_Navigation#2]
Dear author, 

Thank you for sharing the excellent work!!!

I'm trying to run the "run_experiment.py" to evaluate the pre-trained models. 

I'm wondering how can I visualize the evaluation of the results from "run_experiment.py" like you did in the README.md. I will be grateful if you could share the procedures. 

Thank you very much.

**Comment by bexilin** [comment]
Hi, a new script named visualize_exp_episode.py is now included in the scripts directory. You can visualize an experiment episode by setting the corresponding result filename, episode_id and agent.
